// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.ts";
import * as $1 from "./routes/api.tsx";
import * as $2 from "./routes/api/[content].tsx";
import * as $3 from "./routes/api/[content]/[count].ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Footer.tsx";
import * as $$1 from "./islands/Forcem.tsx";

const manifest = {
  routes: {
    "./routes/_404.ts": $0,
    "./routes/api.tsx": $1,
    "./routes/api/[content].tsx": $2,
    "./routes/api/[content]/[count].ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Footer.tsx": $$0,
    "./islands/Forcem.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
